-- MySQL Script generated by MySQL Workbench
-- Fri May 10 12:02:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marca` (
  `idmarca` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idmarca`),
  UNIQUE INDEX `idmarca_UNIQUE` (`idmarca` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modelo` (
  `idmodelo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `marca_idmarca` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idmodelo`),
  UNIQUE INDEX `idmodelo_UNIQUE` (`idmodelo` ASC) VISIBLE,
  INDEX `fk_modelo_marca1_idx` (`marca_idmarca` ASC) VISIBLE,
  CONSTRAINT `fk_modelo_marca1`
    FOREIGN KEY (`marca_idmarca`)
    REFERENCES `mydb`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idcategoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idcategoria`),
  UNIQUE INDEX `idcategoria_UNIQUE` (`idcategoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `idestado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idestado`),
  UNIQUE INDEX `idestado_UNIQUE` (`idestado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidade` (
  `idcidade` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `estado_idestado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idcidade`),
  UNIQUE INDEX `idcidade_UNIQUE` (`idcidade` ASC) VISIBLE,
  INDEX `fk_cidade_estado1_idx` (`estado_idestado` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_idestado`)
    REFERENCES `mydb`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proprietario` (
  `cpf` BIGINT(11) UNSIGNED NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  `cep` BIGINT(8) NOT NULL,
  `data_nascimento` DATETIME NOT NULL,
  `sexo` INT(1) NOT NULL,
  `cidade_idcidade` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `idproprietario_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_proprietario_cidade1_idx` (`cidade_idcidade` ASC) VISIBLE,
  CONSTRAINT `fk_proprietario_cidade1`
    FOREIGN KEY (`cidade_idcidade`)
    REFERENCES `mydb`.`cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cor` (
  `idcor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcor`),
  UNIQUE INDEX `idcor_UNIQUE` (`idcor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`veiculo` (
  `renavam` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `chassi` VARCHAR(50) NOT NULL,
  `placa` VARCHAR(50) NOT NULL,
  `ano_fabricação` YEAR NOT NULL,
  `ano_do_modelo` YEAR NOT NULL,
  `modelo_idmodelo` INT UNSIGNED NOT NULL,
  `idcategoria` INT UNSIGNED NOT NULL,
  `proprietario_cpf` BIGINT(11) UNSIGNED NOT NULL,
  `cor_idcor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`renavam`),
  UNIQUE INDEX `idveiculo_UNIQUE` (`renavam` ASC) VISIBLE,
  UNIQUE INDEX `chassi_UNIQUE` (`chassi` ASC) VISIBLE,
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC) VISIBLE,
  INDEX `fk_veiculo_modelo_idx` (`modelo_idmodelo` ASC) VISIBLE,
  INDEX `fk_veiculo_categoria1_idx` (`idcategoria` ASC) VISIBLE,
  INDEX `fk_veiculo_proprietario1_idx` (`proprietario_cpf` ASC) VISIBLE,
  INDEX `fk_veiculo_cor1_idx` (`cor_idcor` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_modelo`
    FOREIGN KEY (`modelo_idmodelo`)
    REFERENCES `mydb`.`modelo` (`idmodelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_categoria1`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `mydb`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_proprietario1`
    FOREIGN KEY (`proprietario_cpf`)
    REFERENCES `mydb`.`proprietario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_cor1`
    FOREIGN KEY (`cor_idcor`)
    REFERENCES `mydb`.`cor` (`idcor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`combustivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`combustivel` (
  `idcombustivel` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idcombustivel`),
  UNIQUE INDEX `idcombustivel_UNIQUE` (`idcombustivel` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefone` (
  `idtelefone` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero` BIGINT(9) NOT NULL,
  `ddd` INT(2) NOT NULL,
  `proprietario_cpf` BIGINT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`idtelefone`),
  UNIQUE INDEX `idtelefone_UNIQUE` (`idtelefone` ASC) VISIBLE,
  INDEX `fk_telefone_proprietario1_idx` (`proprietario_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_telefone_proprietario1`
    FOREIGN KEY (`proprietario_cpf`)
    REFERENCES `mydb`.`proprietario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modelo` (
  `idmodelo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `marca_idmarca` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idmodelo`),
  UNIQUE INDEX `idmodelo_UNIQUE` (`idmodelo` ASC) VISIBLE,
  INDEX `fk_modelo_marca1_idx` (`marca_idmarca` ASC) VISIBLE,
  CONSTRAINT `fk_modelo_marca1`
    FOREIGN KEY (`marca_idmarca`)
    REFERENCES `mydb`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agente_transito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agente_transito` (
  `idagente_transito` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_contratacao` DATETIME NOT NULL,
  PRIMARY KEY (`idagente_transito`),
  UNIQUE INDEX `idagente_transito_UNIQUE` (`idagente_transito` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_infracoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_infracoes` (
  `idtipo_infracoes` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`idtipo_infracoes`),
  UNIQUE INDEX `idtipo_infracoes_UNIQUE` (`idtipo_infracoes` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`infracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`infracao` (
  `idinfracao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_hora_infracao` DATETIME NOT NULL,
  `local_infracao` VARCHAR(100) NOT NULL,
  `velocidade_aferida` INT NULL,
  `observacoes` TEXT NULL,
  `veiculo_renavam` INT UNSIGNED NOT NULL,
  `idagente_transito` INT UNSIGNED NULL,
  `idtipo_infracoes` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idinfracao`),
  UNIQUE INDEX `idinfracao_UNIQUE` (`idinfracao` ASC) VISIBLE,
  INDEX `fk_infracao_veiculo1_idx` (`veiculo_renavam` ASC) VISIBLE,
  INDEX `fk_infracao_agente_transito1_idx` (`idagente_transito` ASC) VISIBLE,
  INDEX `fk_infracao_tipo_infracoes1_idx` (`idtipo_infracoes` ASC) VISIBLE,
  CONSTRAINT `fk_infracao_veiculo1`
    FOREIGN KEY (`veiculo_renavam`)
    REFERENCES `mydb`.`veiculo` (`renavam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_infracao_agente_transito1`
    FOREIGN KEY (`idagente_transito`)
    REFERENCES `mydb`.`agente_transito` (`idagente_transito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_infracao_tipo_infracoes1`
    FOREIGN KEY (`idtipo_infracoes`)
    REFERENCES `mydb`.`tipo_infracoes` (`idtipo_infracoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo_has_combustivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`veiculo_has_combustivel` (
  `veiculo_renavam` INT UNSIGNED NOT NULL,
  `combustivel_idcombustivel` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`veiculo_renavam`, `combustivel_idcombustivel`),
  INDEX `fk_veiculo_has_combustivel_combustivel1_idx` (`combustivel_idcombustivel` ASC) VISIBLE,
  INDEX `fk_veiculo_has_combustivel_veiculo1_idx` (`veiculo_renavam` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_has_combustivel_veiculo1`
    FOREIGN KEY (`veiculo_renavam`)
    REFERENCES `mydb`.`veiculo` (`renavam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_has_combustivel_combustivel1`
    FOREIGN KEY (`combustivel_idcombustivel`)
    REFERENCES `mydb`.`combustivel` (`idcombustivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
