-- MySQL Script generated by MySQL Workbench
-- Tue Jun  4 11:00:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idestado`),
  UNIQUE INDEX `idestado_UNIQUE` (`idestado` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cidade` (
  `idcidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `estado_idestado` INT NOT NULL,
  PRIMARY KEY (`idcidade`),
  UNIQUE INDEX `idcidade_UNIQUE` (`idcidade` ASC),
  INDEX `fk_cidade_estado1_idx` (`estado_idestado` ASC),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_idestado`)
    REFERENCES `mydb`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` BIGINT(11) NOT NULL,
  `endereco` VARCHAR(100) NULL,
  `data_contratacao` DATE NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `idcidade` INT NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_funcionario_cidade1_idx` (`idcidade` ASC),
  CONSTRAINT `fk_funcionario_cidade1`
    FOREIGN KEY (`idcidade`)
    REFERENCES `mydb`.`cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veterinario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`veterinario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`veterinario` (
  `crv` INT(5) NOT NULL,
  `funcionario_idfuncionario` INT NOT NULL,
  PRIMARY KEY (`funcionario_idfuncionario`),
  UNIQUE INDEX `crv_UNIQUE` (`crv` ASC),
  INDEX `fk_veterinario_funcionario1_idx` (`funcionario_idfuncionario` ASC),
  CONSTRAINT `fk_veterinario_funcionario1`
    FOREIGN KEY (`funcionario_idfuncionario`)
    REFERENCES `mydb`.`funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`especie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`especie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`especie` (
  `idespecie` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idespecie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_dono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente_dono` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente_dono` (
  `idcliente_dono` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(100) NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `cidade_idcidade` INT NOT NULL,
  PRIMARY KEY (`idcliente_dono`),
  INDEX `fk_cliente_dono_cidade1_idx` (`cidade_idcidade` ASC),
  CONSTRAINT `fk_cliente_dono_cidade1`
    FOREIGN KEY (`cidade_idcidade`)
    REFERENCES `mydb`.`cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`animal_paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`animal_paciente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`animal_paciente` (
  `idpaciente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NULL,
  `idespecie` INT NOT NULL,
  `idcliente_dono` INT NOT NULL,
  `massa_kg` DECIMAL(10,2) NOT NULL,
  `alergico` TINYINT NOT NULL,
  PRIMARY KEY (`idpaciente`),
  INDEX `fk_animal_especie1_idx` (`idespecie` ASC),
  INDEX `fk_animal_paciente_cliente_dono1_idx` (`idcliente_dono` ASC),
  CONSTRAINT `fk_animal_especie1`
    FOREIGN KEY (`idespecie`)
    REFERENCES `mydb`.`especie` (`idespecie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_paciente_cliente_dono1`
    FOREIGN KEY (`idcliente_dono`)
    REFERENCES `mydb`.`cliente_dono` (`idcliente_dono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atendimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`atendimento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`atendimento` (
  `idconsulta` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `idpaciente` INT NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `diagnostico` TEXT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idconsulta`),
  INDEX `fk_consulta_animal_paciente1_idx` (`idpaciente` ASC),
  CONSTRAINT `fk_consulta_animal_paciente1`
    FOREIGN KEY (`idpaciente`)
    REFERENCES `mydb`.`animal_paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`procedimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`procedimento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`procedimento` (
  `idprocedimento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idatendimento` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprocedimento`),
  UNIQUE INDEX `idprocedimento_UNIQUE` (`idprocedimento` ASC),
  INDEX `fk_procedimento_atendimento1_idx` (`idatendimento` ASC),
  CONSTRAINT `fk_procedimento_atendimento1`
    FOREIGN KEY (`idatendimento`)
    REFERENCES `mydb`.`atendimento` (`idconsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor` (
  `idfornecedor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cnpj` BIGINT(14) NOT NULL,
  `inscricao_estadual` BIGINT(9) NOT NULL,
  `endereco` VARCHAR(100) NULL,
  `cidade_idcidade` INT NOT NULL,
  `tel_contato` BIGINT(11) NOT NULL,
  PRIMARY KEY (`idfornecedor`),
  UNIQUE INDEX `idfornecedor_UNIQUE` (`idfornecedor` ASC),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC),
  INDEX `fk_fornecedor_cidade1_idx` (`cidade_idcidade` ASC),
  CONSTRAINT `fk_fornecedor_cidade1`
    FOREIGN KEY (`cidade_idcidade`)
    REFERENCES `mydb`.`cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`medicamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`medicamento` (
  `idmedicamento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_validade` DATE NOT NULL,
  `data_fabricacao` DATE NOT NULL,
  `data_compra` DATE NOT NULL,
  `valor_aplicacao` DECIMAL(10,2) NOT NULL,
  `fornecedor_idfornecedor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idmedicamento`),
  UNIQUE INDEX `idmedicamento_UNIQUE` (`idmedicamento` ASC),
  INDEX `fk_medicamento_fornecedor1_idx` (`fornecedor_idfornecedor` ASC),
  CONSTRAINT `fk_medicamento_fornecedor1`
    FOREIGN KEY (`fornecedor_idfornecedor`)
    REFERENCES `mydb`.`fornecedor` (`idfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario_has_atendimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`funcionario_has_atendimento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`funcionario_has_atendimento` (
  `funcionario_idfuncionario` INT NOT NULL,
  `atendimento_idconsulta` INT NOT NULL,
  PRIMARY KEY (`funcionario_idfuncionario`, `atendimento_idconsulta`),
  INDEX `fk_funcionario_has_atendimento_atendimento1_idx` (`atendimento_idconsulta` ASC),
  INDEX `fk_funcionario_has_atendimento_funcionario1_idx` (`funcionario_idfuncionario` ASC),
  CONSTRAINT `fk_funcionario_has_atendimento_funcionario1`
    FOREIGN KEY (`funcionario_idfuncionario`)
    REFERENCES `mydb`.`funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_has_atendimento_atendimento1`
    FOREIGN KEY (`atendimento_idconsulta`)
    REFERENCES `mydb`.`atendimento` (`idconsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atendimento_has_medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`atendimento_has_medicamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`atendimento_has_medicamento` (
  `atendimento_idconsulta` INT NOT NULL,
  `medicamento_idmedicamento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`atendimento_idconsulta`, `medicamento_idmedicamento`),
  INDEX `fk_atendimento_has_medicamento_medicamento1_idx` (`medicamento_idmedicamento` ASC),
  INDEX `fk_atendimento_has_medicamento_atendimento1_idx` (`atendimento_idconsulta` ASC),
  CONSTRAINT `fk_atendimento_has_medicamento_atendimento1`
    FOREIGN KEY (`atendimento_idconsulta`)
    REFERENCES `mydb`.`atendimento` (`idconsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atendimento_has_medicamento_medicamento1`
    FOREIGN KEY (`medicamento_idmedicamento`)
    REFERENCES `mydb`.`medicamento` (`idmedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vacina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vacina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vacina` (
  `nome` VARCHAR(100) NOT NULL,
  `doenca_prevenida` VARCHAR(100) NOT NULL,
  `valor_aplicacao` DECIMAL(10,2) NOT NULL,
  `descricao` TEXT NULL,
  `procedimento_idprocedimento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`procedimento_idprocedimento`),
  INDEX `fk_vacina_procedimento1_idx` (`procedimento_idprocedimento` ASC),
  CONSTRAINT `fk_vacina_procedimento1`
    FOREIGN KEY (`procedimento_idprocedimento`)
    REFERENCES `mydb`.`procedimento` (`idprocedimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;